---
language: go
sudo: false
notifications:
  email: joaosoft@gmail.com
jobs:
  include:
    - stage: test
      install:
        - go get github.com/joaosoft/dependency
        - dependency get
      os: linux
      go: master
      script:
        - go build ./basic
        - go build ./jwt
        - go test ./basic
        - go test ./jwt
        - go test -coverprofile=coverage.txt -covermode=atomic ./basic
        - go test -coverprofile=coverage.txt -covermode=atomic ./jwt
        - go test ./basic -bench=. -cpu=1,2,4,8
        - go test ./jwt -bench=. -cpu=1,2,4,8

      after_success:
        - bash <(curl -s https://codecov.io/bash)